rails-chat-app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  root 'messages#index'

end

rails-chat-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-chat-app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

rails-chat-app/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

rails-chat-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :messages
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

rails-chat-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

rails-chat-app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message, only: [:create, :edit, :update, :destroy]
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
    @message = Message.find(params[:message_id])
  end

  def find_comment
    @comment = @message.comments.find(params[:id])
  end

end

rails-chat-app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end

  def find_message
    @message = Message.find(params[:id])
  end
end

rails-chat-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-chat-app/app/helpers/comments_helper.rb
module CommentsHelper
end

rails-chat-app/app/helpers/messages_helper.rb
module MessagesHelper
end

rails-chat-app/app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">By <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>
</div>

rails-chat-app/app/views/comments/_form.html.erb
<%= simple_form_for ([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comments" %>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

rails-chat-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsChatApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id="body">
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <div class="container">
      <%= link_to "chat-app", root_path, class: "navbar-brand" %>
    </div>
    <ul class="navbar-nav nav navbar">
      <% if user_signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
      <p><%= link_to "Post It", new_message_path, class: "navbar-text navbar-link" %></p>
    <% end %>
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

rails-chat-app/app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

rails-chat-app/app/views/messages/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header">Fix Message</h1>
  <%= render 'form' %>
</div>

rails-chat-app/app/views/messages/index.html.erb
<% @messages.each do |m| %>
  <div class="col-md-10.col-md-offset-1">
    <div class="message">
      <h2 class="message-title"><%= m.title %></h2>
      <%= link_to "Join Conversation", m, class: "btn-custom" %>
    </div>
  </div>
<% end %>
<%= link_to "Post meesage", new_message_path %>

rails-chat-app/app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header">Post Message</h1>
  <%= render 'form' %>
</div>

rails-chat-app/app/views/messages/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="message-show">
    <h2><%= @message.title %></h2>
    <p class="message-posted-by"><%= time_ago_in_words(@message.created_at) %> ago </p>
    <p class="message-desc"><%= @message.description %></p>

    <h3 class="comment-section-header">Comments:</h3>
    <p><%= render @message.comments %></p>

    <h3 class="reply-to-msg">Join Discussion:</h3>
    <%= render 'comments/form' %>

    <div class="links btn-group">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
    </div>
  </div>
</div>